version: '3.1'

services:

  db:
    image: mysql
    restart: always
    container_name: MySQL-database
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'p2p_database'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    restart: unless-stopped
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - "3000:3000"
      - "3001:3001"
    cap_add:
      - IPC_LOCK
    links:
      - db